version: "3.5"

services:
  back:
    build:
      context: ${BASE_PATH}
      dockerfile: ${BASE_PATH}/DockerFile
    container_name: ${PROJECT_NAME}-${MS_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.projectName.rule=Host(`backend.${DOMAIN}`)"
      - "traefik.http.routers.projectName.entrypoints=web"
      - "traefik.http.routers.projectName.service=etradeService"
      - "traefik.http.services.etradeService.loadBalancer.server.port=${BACK_PORT}"

    restart: always
    ports:
      - 9000:9000
    volumes:
      - ${BASE_PATH}/:/src
      - ../public/:/public
    networks:
      - relay-net
      - database-net
    environment:
      - TZ=Africa/Tunis

networks:
  relay-net:
    name: "${PROJECT_NAME}-${RELAY_NETWORK}"
    external: true
  database-net:
    name: "${PROJECT_NAME}-database"
    external: true